external_components:
  - source: github://jrollinson/esphome-vornado-fan@main
    # refresh: always  # Uncomment during development
    components: [ vornado_controller, vornado_stateful_controller ]

packages:
  vornado_buttons: github://jrollinson/esphome-vornado-fan/buttons.yaml@main

esphome:
  name: kitchen-fan-controller
  friendly_name: "Kitchen Fan"

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # domain: ".your.domain"
  min_auth_mode: WPA2
  fast_connect: true
  power_save_mode: none

  ap:
    ssid: "Vornado-Fan-Fallback"
    password: !secret wifi_ap_password

captive_portal:

logger:
  level: INFO
  logs:
    vornado_controller: INFO
    vornado_stateful: INFO

api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 15min

ota:
  - platform: esphome
    password: !secret ota_password

remote_transmitter:
  id: ir_tx
  pin: GPIO4
  carrier_duty_percent: 50%

vornado_controller:
  id: vornado_ctrl
  transmitter_id: ir_tx

vornado_stateful_controller:
  id: vornado_stateful
  name: "Vornado Fan"
  controller: vornado_ctrl
